### ISSUE TITLE
添加README

### ISSUE THREAD

**Issue by gkqzdxajh** [gkqzdxajh/weekreport#2]
便于大家了解你的项目

**Comment by gkqzdxajh** [comment]
@gkqzdxbjh 你有什么好主意？

**Comment by gkqzdxbjh** [comment]
> 你有什么好主意？

这个问题已经讨论过了，详见https://github.com/gkqzdxajh/weekreport/issues/2#issue-103487500
此处是点击'commented Xx minutes ago'时的超链接

**Comment by gkqzdxbjh** [comment]
#1 PullRequest与Issues都是由编号**#Xx**来确定的

**Comment by gkqzdxajh** [comment]
语法高亮显示测试
- javascript语法

``` js
console.log('使用3个波浪号Tab键上面');
```
- java语法

```
System.out.println('Hello,Java');
```
